Expand and improve unit test for rust code
julienbrs/Offsetter-merkle-tree pull request #6
Opened 2024-11-22 12:27 UTC by codebestia

Resolves #3

2024-11-27 03:52 UTC, codebestia commented
@julienbrs please review

2024-11-27 14:44 UTC, julienbrs requested changes
LGTM, please just run cargo fmt and it's good to go, congrats

2024-11-27 15:15 UTC, codebestia commented
> LGTM, please just run cargo fmt and it's good to go, congrats

Done.. Thanks

2024-11-28 15:27 UTC, julienbrs approved these changes

2024-11-28 15:28 UTC, merged